# Generated by Django 4.2.5 on 2023-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uva_maps', '0005_feedback_rating_placerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='placerating',
            name='user',
            field=models.CharField(default='none'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='placerating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
